/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.blockchain.cardano

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class CardanoAggregateSumValue (
	val value: String? = null
)

@Serializable
data class CardanoAggregateSum (
	val sum: CardanoAggregateSumValue
)

@Serializable
data class CardanoAggregateBalance (
	val aggregate: CardanoAggregateSum
)

@Serializable
data class CardanoBalance (
	val address: String,
	val txHash: String,
	val index: Int
)

@Serializable
data class CardanoBlock (
	val number: Int
)

@Serializable
data class CardanoBlockTip (
	val tip: CardanoBlock
)

@Serializable
data class CardanoBlockData (
	val cardano: CardanoBlockTip
)

@Serializable
data class CardanoSubmitTransactionHash (
	val hash: String
)

@Serializable
data class CardanoTransaction (
	val fee: String,
	val block: CardanoBlock
)

@Serializable
data class CardanoTransactionBroadcast (
	val submitTransaction: CardanoSubmitTransactionHash
)

@Serializable
data class CardanoTransactions (
	val transactions: List<CardanoTransaction>
)

@Serializable
data class CardanoUTXO (
	val address: String,
	val txHash: String,
	val index: Int,
	val value: String
)

@Serializable
data class CardanoUTXOS<T> (
	val utxos: T
)

