/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.blockchain.graphql

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class GraphqlData<T> (
	val data: T
)

@Serializable
data class GraphqlError (
	val message: String
)

@Serializable
data class GraphqlRequest (
	val operationName: String,
	val variables: HashMap<String, String>,
	val query: String
)

