/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.blockchain.graphql

import kotlinx.serialization.Serializable

@Serializable
data class GraphqlError (
	val message: String
)

@Serializable
data class GraphqlData<T> (
	val data: T? = null,
	val errors: List<GraphqlError>? = null
)

@Serializable
data class GraphqlRequest (
	val operationName: String,
	val variables: HashMap<String, String>,
	val query: String
)

