/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.cardano

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class CardanoAggregateSumValue (
	val value: String? = null
)

@Serializable
data class CardanoAggregateSum (
	val sum: CardanoAggregateSumValue
)

@Serializable
data class CardanoAggregateBalance (
	val aggregate: CardanoAggregateSum
)

@Serializable
data class CardanoBalance (
	val address: String,
	val txHash: String,
	val index: Int
)

