/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.cardano

import kotlinx.serialization.Serializable

@Serializable
data class CardanoBlock (
	val number: Long
)

@Serializable
data class CardanoBlockTip (
	val tip: CardanoBlock
)

@Serializable
data class CardanoBlockData (
	val cardano: CardanoBlockTip
)

@Serializable
data class CardanoGenesisShelley (
	val networkMagic: Int
)

@Serializable
data class CardanoGenesis (
	val shelley: CardanoGenesisShelley
)

@Serializable
data class CardanoGenesisData (
	val genesis: CardanoGenesis
)

