/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.cardano

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class CardanoUTXO (
	val address: String,
	val txHash: String,
	val index: Int,
	val value: String
)

@Serializable
data class CardanoUTXOS<T> (
	val utxos: T
)

