pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
    }
}
rootProject.name = "wallet"
include (":app")
include(":blockchain")
include(":gemcore")
include(":ui")
include(":ui-models")
include(":data")
include(":data:services")
include(":data:services:store")
include(":data:repositories")
include(":data:services:remote-gem")
include(":flavors")
include(":flavors:pushes-stub")
include(":flavors:fcm")
include(":features")
include(":features:recipient")
include(":features:recipient:viewmodels")
include(":features:recipient:presents")
include(":features:nft")
include(":features:nft:presents")
include(":features:nft:viewmodels")
include(":features:update_app")
include(":features:update_app:presents")
include(":features:update_app:viewmodels")
include(":features:wallet-details")
include(":features:wallet-details:presents")
include(":features:wallet-details:viewmodels")
include(":features:activities")
include(":features:activities:presents")
include(":features:activities:viewmodels")
include(":flavors:google-review")
include(":flavors:review-stub")