/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.near

import kotlinx.serialization.Serializable

@Serializable
data class NearAccount (
	val amount: String
)

@Serializable
data class NearAccountAccessKey (
	val nonce: Long
)

