/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.near

import kotlinx.serialization.Serializable

@Serializable
data class NearError (
	val message: String,
	val data: String? = null
)

@Serializable
data class NearRPCError (
	val error: NearError
)

