/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.near

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class NearGasPrice (
	val gas_price: String
)

