/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.near

import kotlinx.serialization.Serializable

@Serializable
data class NearBroadcastTransaction (
	val hash: String
)

@Serializable
data class NearBroadcastResult (
	val final_execution_status: String,
	val transaction: NearBroadcastTransaction
)

