/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.bitcoin

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class BitcoinBlock (
	val previousBlockHash: String? = null
)

@Serializable
data class BitcoinBlockbook (
	val inSync: Boolean,
	val lastBlockTime: String,
	val bestHeight: Long
)

@Serializable
data class BitcoinNodeInfo (
	val blockbook: BitcoinBlockbook
)

