/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.bitcoin

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class BitcoinTransaction (
	val blockHeight: Long
)

@Serializable
data class BitcoinTransactionBroacastError (
	val message: String
)

@Serializable
data class BitcoinTransactionBroacastResult (
	val error: BitcoinTransactionBroacastError? = null,
	val result: String? = null
)

@Serializable
data class BitcoinUTXO (
	val txid: String,
	val vout: Int,
	val value: String
)

