/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.ethereum

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class EthereumBlockParameter(val string: String) {
	@SerialName("latest")
	Latest("latest"),
	@SerialName("earliest")
	Earliest("earliest"),
	@SerialName("pending")
	Pending("pending"),
	@SerialName("finalized")
	Finalized("finalized"),
	@SerialName("safe")
	Safe("safe"),
}

