/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.ethereum

import kotlinx.serialization.Serializable

@Serializable
data class EthereumFeeHistory (
	val reward: List<List<String>>,
	val baseFeePerGas: List<String>,
	val gasUsedRatio: List<Double>,
	val oldestBlock: String
)

