/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.ethereum

import kotlinx.serialization.Serializable

@Serializable
data class EthereumTransactionReciept (
	val status: String,
	val gasUsed: String,
	val effectiveGasPrice: String,
	val l1Fee: String? = null
)

