/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.blockchain.aptos.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class AptosAccount (
	val sequence_number: String
)

@Serializable
data class AptosGasFee (
	val gas_estimate: Int,
	val prioritized_gas_estimate: Int
)

@Serializable
data class AptosLedger (
	val chain_id: Int,
	val ledger_version: String
)

@Serializable
data class AptosResource<T> (
	val type: String,
	val data: T
)

@Serializable
data class AptosResourceCoin (
	val value: String
)

@Serializable
data class AptosResourceBalance (
	val coin: AptosResourceCoin
)

@Serializable
data class AptosTransaction (
	val success: Boolean
)

@Serializable
data class AptosTransactionBroacast (
	val hash: String
)

