/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.blockchain.aptos.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class AptosAccount (
	val sequence_number: String
)

@Serializable
data class AptosCoinInfo (
	val decimals: Int,
	val name: String,
	val symbol: String
)

@Serializable
data class AptosError (
	val message: String,
	val error_code: String
)

@Serializable
data class AptosGasFee (
	val deprioritized_gas_estimate: Int,
	val gas_estimate: Int,
	val prioritized_gas_estimate: Int
)

@Serializable
data class AptosLedger (
	val chain_id: Int,
	val ledger_version: String
)

@Serializable
data class AptosResource<T> (
	val type: String,
	val data: T
)

@Serializable
data class AptosResourceCoin (
	val value: String
)

@Serializable
data class AptosResourceBalance (
	val coin: AptosResourceCoin
)

@Serializable
data class AptosResourceBalanceOptional (
	val coin: AptosResourceCoin? = null
)

@Serializable
data class AptosTransaction (
	val success: Boolean,
	val gas_used: String,
	val gas_unit_price: String
)

@Serializable
data class AptosTransactionBroacast (
	val hash: String
)

@Serializable
enum class AptosErrorCode(val string: String) {
	@SerialName("account_not_found")
	account_not_found("account_not_found"),
}

