/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.solana

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class SolanaBalance (
	val value: Long
)

@Serializable
data class SolanaBalanceValue (
	val amount: String
)

