/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.solana

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class SolanaAccountMeta (
	val pubkey: String,
	val isSigner: Boolean,
	val isWritable: Boolean
)

@Serializable
data class SolanaInstruction (
	val programId: String,
	val accounts: List<SolanaAccountMeta>,
	val data: String
)

@Serializable
object SolanaTransactionError

@Serializable
data class SolanaTransactionMeta (
	val err: SolanaTransactionError? = null
)

@Serializable
data class SolanaTransaction (
	val meta: SolanaTransactionMeta,
	val slot: Long
)

