/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.blockchain.algorand

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class AlgorandAccount (
	val amount: Long
)

@Serializable
data class AlgorandTransactionBroadcast (
	val txId: String
)

@Serializable
data class AlgorandTransactionBroadcastError (
	val message: String
)

@Serializable
data class AlgorandTransactionParams (
	@SerialName("min-fee")
	val min_fee: Int,
	@SerialName("genesis-id")
	val genesis_id: String,
	@SerialName("genesis-hash")
	val genesis_hash: String,
	@SerialName("last-round")
	val last_round: Int
)

@Serializable
data class AlgorandTransactionStatus (
	@SerialName("confirmed-round")
	val confirmed_round: Int
)

@Serializable
data class AlgorandVersions (
	@SerialName("genesis-id")
	val genesis_id: String,
	@SerialName("genesis-hash")
	val genesis_hash: String
)

