/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.blockchain.ethereum.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class EthereumFeeHistory (
	val reward: List<List<String>>,
	val baseFeePerGas: List<String>
)

@Serializable
data class EthereumTransactionReciept (
	val status: String,
	val gasUsed: String,
	val effectiveGasPrice: String,
	val l1Fee: String? = null
)

