/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.polkadot

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class PolkadotAccountBalance (
	val free: String,
	val reserved: String,
	val nonce: String
)

