/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.polkadot

import kotlinx.serialization.Serializable

@Serializable
data class PolkadotExtrinsic (
	val hash: String,
	val success: Boolean
)

@Serializable
data class PolkadotBlock (
	val number: String,
	val extrinsics: List<PolkadotExtrinsic>
)

@Serializable
data class PolkadotNodeVersion (
	val chain: String
)

