/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.polkadot

import kotlinx.serialization.Serializable

@Serializable
data class PolkadotEstimateFee (
	val partialFee: String
)

