/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.tron

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class TronChainParameter (
	val key: String,
	val value: Long? = null
)

@Serializable
data class TronChainParameters (
	val chainParameter: List<TronChainParameter>
)

@Serializable
enum class TronChainParameterKey(val string: String) {
	@SerialName("getCreateNewAccountFeeInSystemContract")
	GetCreateNewAccountFeeInSystemContract("getCreateNewAccountFeeInSystemContract"),
	@SerialName("getCreateAccountFee")
	GetCreateAccountFee("getCreateAccountFee"),
	@SerialName("getEnergyFee")
	GetEnergyFee("getEnergyFee"),
}

