/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.aptos

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class AptosAccount (
	val sequence_number: String
)

