/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.aptos

import kotlinx.serialization.Serializable

@Serializable
data class AptosGasFee (
	val deprioritized_gas_estimate: Long,
	val gas_estimate: Long,
	val prioritized_gas_estimate: Long
)

