/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.aptos

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class AptosResource<T> (
	val type: String,
	val data: T
)

@Serializable
data class AptosResourceCoin (
	val value: String
)

@Serializable
data class AptosResourceBalance (
	val coin: AptosResourceCoin
)

@Serializable
data class AptosResourceBalanceOptional (
	val coin: AptosResourceCoin? = null
)

