/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.sui

import kotlinx.serialization.Serializable

@Serializable
data class SuiCoin (
	val coinType: String,
	val coinObjectId: String,
	val balance: String,
	val version: String,
	val digest: String
)

@Serializable
data class SuiCoinBalance (
	val coinType: String,
	val totalBalance: String
)

@Serializable
data class SuiCoinMetadata (
	val decimals: Int,
	val name: String,
	val symbol: String
)

