/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.sui

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class SuiAddStakeRequest (
	val senderAddress: String,
	val validatorAddress: String,
	val coins: List<String>,
	val amount: String,
	val gasBudget: String
)

@Serializable
data class SuiBatchRequest (
	val senderAddress: String,
	val gasBudget: String
)

@Serializable
data class SuiMoveCallRequest (
	val senderAddress: String,
	val objectId: String,
	val module: String,
	val function: String,
	val arguments: List<String>,
	val gasBudget: String
)

@Serializable
data class SuiPay (
	val txBytes: String
)

@Serializable
data class SuiPayRequest (
	val senderAddress: String,
	val recipientAddress: String,
	val coins: List<String>,
	val gas: String? = null,
	val amount: String,
	val gasBudget: String
)

@Serializable
data class SuiSplitCoinRequest (
	val senderAddress: String,
	val coin: String,
	val splitAmounts: List<String>,
	val gasBudget: String
)

@Serializable
data class SuiUnstakeRequest (
	val senderAddress: String,
	val delegationId: String,
	val gasBudget: String
)

