/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.sui

import kotlinx.serialization.Serializable

@Serializable
data class SuiStake (
	val stakedSuiId: String,
	val status: String,
	val principal: String,
	val stakeRequestEpoch: String,
	val stakeActiveEpoch: String,
	val estimatedReward: String? = null
)

@Serializable
data class SuiStakeDelegation (
	val validatorAddress: String,
	val stakingPool: String,
	val stakes: List<SuiStake>
)

@Serializable
data class SuiSystemState (
	val epoch: String,
	val epochStartTimestampMs: String,
	val epochDurationMs: String
)

@Serializable
data class SuiValidator (
	val address: String,
	val apy: Double
)

@Serializable
data class SuiValidators (
	val apys: List<SuiValidator>
)

