/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.sui

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class SuiData<T> (
	val data: T
)

