/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.sui

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class SuiBroadcastTransaction (
	val digest: String
)

@Serializable
data class SuiGasUsed (
	val computationCost: String,
	val storageCost: String,
	val storageRebate: String,
	val nonRefundableStorageFee: String
)

@Serializable
data class SuiStatus (
	val status: String
)

@Serializable
data class SuiObjectReference (
	val objectId: String
)

@Serializable
data class SuiObjectChange (
	val reference: SuiObjectReference
)

@Serializable
data class SuiEffects (
	val gasUsed: SuiGasUsed,
	val status: SuiStatus,
	val created: List<SuiObjectChange>? = null
)

@Serializable
data class SuiTransaction (
	val effects: SuiEffects
)

