/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.blockchain.ton.models

import kotlinx.serialization.Serializable

@Serializable
data class TonBroadcastTransaction (
	val hash: String
)

