/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.blockchain.ton.models

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class TonBlock (
	val seqno: Int,
	val root_hash: String
)

@Serializable
data class TonMasterchainInfo (
	val last: TonBlock
)

