/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.blockchain.ton.models

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class TonEstimateFee (
	val address: String,
	val body: String,
	val ignore_chksig: Boolean
)

@Serializable
data class TonFee (
	val in_fwd_fee: Int,
	val storage_fee: Int
)

@Serializable
data class TonFees (
	val source_fees: TonFee
)

