/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.ton.models

import kotlinx.serialization.Serializable

@Serializable
data class TonJettonBalance (
	val balance: Long
)

@Serializable
data class TonJettonTokenContentData (
	val name: String,
	val symbol: String,
	val decimals: String
)

@Serializable
data class TonJettonTokenContent (
	val type: String,
	val data: TonJettonTokenContentData
)

@Serializable
data class TonJettonToken (
	val jetton_content: TonJettonTokenContent
)

@Serializable
data class TonTransactionOutMessage (
	val hash: String,
	val bounce: Boolean,
	val bounced: Boolean
)

@Serializable
data class TonTransactionMessage (
	val hash: String,
	val out_msgs: List<TonTransactionOutMessage>
)

@Serializable
data class TonMessageTransactions (
	val transactions: List<TonTransactionMessage>
)

@Serializable
data class TonTransactionId (
	val hash: String
)

@Serializable
data class TonTransaction (
	val transaction_id: TonTransactionId
)

