/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.ton.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class TonResult<T> (
	val result: T
)

@Serializable
data class TonWalletInfo (
	val seqno: Int? = null,
	val last_transaction_id: TonTransactionId
)

