/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.blockchain.bitcoin.models

import kotlinx.serialization.Serializable

@Serializable
data class BitcoinAccount (
	val balance: String
)

