/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.blockchain.bitcoin.models

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.Serializable

@Serializable
data class BitcoinBlockbook (
	val inSync: Boolean,
	val lastBlockTime: Boolean
)

@Serializable
data class BitcoinNodeInfo (
	val blockbook: BitcoinBlockbook
)

