/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.blockchain.bitcoin.models

import kotlinx.serialization.Serializable

@Serializable
data class BitcoinFeeResult (
	val result: String
)

