/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.bitcoin.models

import kotlinx.serialization.Serializable

@Serializable
data class BitcoinUTXO (
	val txid: String,
	val vout: Int,
	val value: String
)

