/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.blockchain.bitcoin.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class BitcoinBlockbook (
	val inSync: Boolean,
	val lastBlockTime: String,
	val bestHeight: Long
)

@Serializable
data class BitcoinNodeInfo (
	val blockbook: BitcoinBlockbook
)

