/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.blockchain.bitcoin.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class BitcoinBlock (
	val previousBlockHash: String? = null
)

