/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.bitcoin.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class BitcoinFeeResult (
	val result: String
)

