/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives.swap

import com.wallet.core.primitives.SwapProvider
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class ApprovalData (
	val token: String,
	val spender: String,
	val value: String
)

@Serializable
data class QuoteAsset (
	val id: String,
	val symbol: String,
	val decimals: UInt
)

@Serializable
data class SwapProviderData (
	val provider: SwapProvider,
	val name: String,
	val protocolName: String
)

@Serializable
data class SwapQuote (
	val fromAddress: String,
	val fromValue: String,
	val toAddress: String,
	val toValue: String,
	val providerData: SwapProviderData,
	val slippageBps: UInt,
	val etaInSeconds: UInt? = null,
	val useMaxAmount: Boolean? = null
)

@Serializable
enum class SwapQuoteDataType(val string: String) {
	@SerialName("contract")
	Contract("contract"),
	@SerialName("transfer")
	Transfer("transfer"),
}

@Serializable
data class SwapQuoteData (
	val to: String,
	val dataType: SwapQuoteDataType,
	val value: String,
	val data: String,
	val memo: String? = null,
	val approval: ApprovalData? = null,
	val gasLimit: String? = null
)

@Serializable
data class SwapData (
	val quote: SwapQuote,
	val data: SwapQuoteData
)

@Serializable
enum class SwapStatus(val string: String) {
	@SerialName("pending")
	Pending("pending"),
	@SerialName("completed")
	Completed("completed"),
	@SerialName("failed")
	Failed("failed"),
	@SerialName("refunded")
	Refunded("refunded"),
}

