/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.blockchain.stellar

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class StellarBalance (
	val balance: String,
	val asset_type: String
)

@Serializable
data class StellarAccount (
	val sequence: String,
	val balances: List<StellarBalance>
)

@Serializable
data class StellarAccountEmpty (
	val status: Int
)

@Serializable
data class StellarFeeCharged (
	val min: String,
	val p95: String
)

@Serializable
data class StellarFees (
	val last_ledger_base_fee: String,
	val fee_charged: StellarFeeCharged
)

@Serializable
data class StellarNodeStatus (
	val ingest_latest_ledger: Int,
	val network_passphrase: String
)

@Serializable
data class StellarTransactionBroadcast (
	val hash: String
)

@Serializable
data class StellarTransactionBroadcastError (
	val title: String
)

@Serializable
data class StellarTransactionStatus (
	val successful: Boolean,
	val fee_charged: String
)

