/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class AssetOrder(val string: String) {
	@SerialName("priceChange24hAsc")
	PriceChange24hAsc("priceChange24hAsc"),
	@SerialName("priceChange24hDesc")
	PriceChange24hDesc("priceChange24hDesc"),
}

