/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class AssetMetaData (
	val isEnabled: Boolean,
	val isBuyEnabled: Boolean,
	val isSwapEnabled: Boolean,
	val isStakeEnabled: Boolean,
	val isPinned: Boolean
)