/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class AssetMetaData (
	val isEnabled: Boolean,
	val isBuyEnabled: Boolean,
	val isSellEnabled: Boolean,
	val isSwapEnabled: Boolean,
	val isStakeEnabled: Boolean,
	val isPinned: Boolean
)

