/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class Asset (
	val id: AssetId,
	val name: String,
	val symbol: String,
	val decimals: Int,
	val type: AssetType
)

