/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class AssetId (
	val chain: Chain,
	val tokenId: String? = null
)

