/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class AssetScore (
	val rank: Int
)

@Serializable
enum class AssetRank(val string: String) {
	@SerialName("high")
	High("high"),
	@SerialName("medium")
	Medium("medium"),
	@SerialName("low")
	Low("low"),
	@SerialName("trivial")
	Trivial("trivial"),
	@SerialName("unknown")
	Unknown("unknown"),
	@SerialName("inactive")
	Inactive("inactive"),
	@SerialName("abandoned")
	Abandoned("abandoned"),
	@SerialName("suspended")
	Suspended("suspended"),
	@SerialName("migrated")
	Migrated("migrated"),
	@SerialName("deprecated")
	Deprecated("deprecated"),
	@SerialName("spam")
	Spam("spam"),
	@SerialName("fradulent")
	Fradulent("fradulent"),
}

