/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class AssetLinks (
	val homepage: String? = null,
	val explorer: String? = null,
	val twitter: String? = null,
	val telegram: String? = null,
	val github: String? = null,
	val youtube: String? = null,
	val facebook: String? = null,
	val reddit: String? = null,
	val coingecko: String? = null,
	val coinmarketcap: String? = null,
	val discord: String? = null
)

@Serializable
data class AssetDetails (
	val links: AssetLinks,
	val isBuyable: Boolean,
	val isSellable: Boolean,
	val isSwapable: Boolean,
	val isStakeable: Boolean,
	val stakingApr: Double? = null
)

@Serializable
data class AssetFull (
	val asset: Asset,
	val details: AssetDetails? = null,
	val price: Price? = null,
	val market: AssetMarket? = null,
	val score: AssetScore
)

@Serializable
data class AssetMarketPrice (
	val price: Price? = null,
	val market: AssetMarket? = null
)

@Serializable
data class AssetDetailsInfo (
	val details: AssetDetails,
	val market: AssetMarket
)

