/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class AssetMetaData (
	val isEnabled: Boolean,
	val isBuyEnabled: Boolean,
	val isSwapEnabled: Boolean,
	val isStakeEnabled: Boolean,
	val isPinned: Boolean
)

