/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class Asset (
	val id: AssetId,
	val name: String,
	val symbol: String,
	val decimals: Int,
	val type: AssetType
)

