/**
 * Generated by typeshare 1.7.0
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.Serializable

@Serializable
data class Balance (
	val available: String,
	val frozen: String,
	val locked: String,
	val staked: String,
	val pending: String,
	val rewards: String
)

