/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
enum class BannerEvent(val string: String) {
	@SerialName("stake")
	stake("stake"),
	@SerialName("accountActivation")
	account_activation("accountActivation"),
	@SerialName("enableNotifications")
	enable_notifications("enableNotifications"),
}

@Serializable
enum class BannerState(val string: String) {
	@SerialName("active")
	active("active"),
	@SerialName("cancelled")
	cancelled("cancelled"),
	@SerialName("alwaysActive")
	always_active("alwaysActive"),
}

@Serializable
data class Banner (
	val wallet: Wallet? = null,
	val asset: Asset? = null,
	val event: BannerEvent,
	val state: BannerState
)

