/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class CosmosChain(val string: String) {
	@SerialName("cosmos")
	Cosmos("cosmos"),
	@SerialName("osmosis")
	Osmosis("osmosis"),
	@SerialName("celestia")
	Celestia("celestia"),
	@SerialName("thorchain")
	Thorchain("thorchain"),
	@SerialName("injective")
	Injective("injective"),
	@SerialName("sei")
	Sei("sei"),
	@SerialName("noble")
	Noble("noble"),
}

@Serializable
enum class CosmosDenom(val string: String) {
	@SerialName("rune")
	Rune("rune"),
	@SerialName("uatom")
	Uatom("uatom"),
	@SerialName("uosmo")
	Uosmo("uosmo"),
	@SerialName("utia")
	Utia("utia"),
	@SerialName("inj")
	Inj("inj"),
	@SerialName("usei")
	Usei("usei"),
	@SerialName("uusdc")
	Uusdc("uusdc"),
}

