/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class StakeChain(val string: String) {
	@SerialName("cosmos")
	Cosmos("cosmos"),
	@SerialName("osmosis")
	Osmosis("osmosis"),
	@SerialName("injective")
	Injective("injective"),
	@SerialName("sei")
	Sei("sei"),
	@SerialName("celestia")
	Celestia("celestia"),
	@SerialName("solana")
	Solana("solana"),
	@SerialName("sui")
	Sui("sui"),
	@SerialName("smartchain")
	SmartChain("smartchain"),
	@SerialName("tron")
	Tron("tron"),
}

