/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
enum class CosmosChain(val string: String) {
	@SerialName("cosmos")
	Cosmos("cosmos"),
	@SerialName("osmosis")
	Osmosis("osmosis"),
	@SerialName("celestia")
	Celestia("celestia"),
	@SerialName("thorchain")
	Thorchain("thorchain"),
	@SerialName("injective")
	Injective("injective"),
	@SerialName("sei")
	Sei("sei"),
	@SerialName("noble")
	Noble("noble"),
}

@Serializable
enum class CosmosDenom(val string: String) {
	@SerialName("rune")
	rune("rune"),
	@SerialName("uatom")
	uatom("uatom"),
	@SerialName("uosmo")
	uosmo("uosmo"),
	@SerialName("utia")
	utia("utia"),
	@SerialName("inj")
	inj("inj"),
	@SerialName("usei")
	usei("usei"),
	@SerialName("uusdc")
	uusdc("uusdc"),
}

