/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class BitcoinChain(val string: String) {
	@SerialName("bitcoin")
	Bitcoin("bitcoin"),
	@SerialName("litecoin")
	Litecoin("litecoin"),
	@SerialName("doge")
	Doge("doge"),
}

