/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
enum class ChainType(val string: String) {
	@SerialName("ethereum")
	Ethereum("ethereum"),
	@SerialName("bitcoin")
	Bitcoin("bitcoin"),
	@SerialName("solana")
	Solana("solana"),
	@SerialName("cosmos")
	Cosmos("cosmos"),
	@SerialName("ton")
	Ton("ton"),
	@SerialName("tron")
	Tron("tron"),
	@SerialName("aptos")
	Aptos("aptos"),
	@SerialName("sui")
	Sui("sui"),
	@SerialName("xrp")
	Xrp("xrp"),
	@SerialName("near")
	Near("near"),
}

