/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class Device (
	val id: String,
	val platform: Platform,
	val platformStore: PlatformStore? = null,
	val token: String,
	val locale: String,
	val version: String,
	val currency: String,
	val isPushEnabled: Boolean,
	val isPriceAlertsEnabled: Boolean? = null,
	val subscriptionsVersion: Int
)

