/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class EIP712Domain (
	val name: String,
	val version: String,
	val chainId: UInt,
	val verifyingContract: String
)

@Serializable
data class EIP712Type (
	val name: String,
	val type: String
)

