/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class EncodingType(val string: String) {
	@SerialName("Hex")
	Hex("Hex"),
	@SerialName("Base58")
	Base58("Base58"),
}

