/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class ERC2612Permit (
	val owner: String,
	val spender: String,
	val value: String,
	val nonce: String,
	val deadline: String
)

@Serializable
data class ERC2612Types (
	val EIP712Domain: List<EIP712Type>,
	val Permit: List<EIP712Type>
)

@Serializable
data class ERC2612PermitMessage (
	val types: ERC2612Types,
	val primaryType: String,
	val domain: EIP712Domain,
	val message: ERC2612Permit
)

