/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
enum class FeePriority(val string: String) {
	@SerialName("slow")
	slow("slow"),
	@SerialName("normal")
	normal("normal"),
	@SerialName("fast")
	fast("fast"),
}

@Serializable
enum class FeeUnitType(val string: String) {
	@SerialName("satVb")
	satVb("satVb"),
	@SerialName("satB")
	satB("satB"),
}

