/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class FeePriority(val string: String) {
	@SerialName("slow")
	slow("slow"),
	@SerialName("normal")
	normal("normal"),
	@SerialName("fast")
	fast("fast"),
}

@Serializable
enum class FeeUnitType(val string: String) {
	@SerialName("satVb")
	satVb("satVb"),
	@SerialName("satB")
	satB("satB"),
	@SerialName("gwei")
	gwei("gwei"),
}

