/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class FiatQuoteType(val string: String) {
	@SerialName("buy")
	Buy("buy"),
	@SerialName("sell")
	Sell("sell"),
}

@Serializable
data class FiatQuote (
	val provider: FiatProvider,
	val type: FiatQuoteType,
	val fiatAmount: Double,
	val fiatCurrency: String,
	val cryptoAmount: Double,
	val redirectUrl: String
)

@Serializable
data class FiatQuotes (
	val quotes: List<FiatQuote>
)

