/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class FiatTransactionType(val string: String) {
	@SerialName("buy")
	Buy("buy"),
	@SerialName("sell")
	Sell("sell"),
}

