/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class FiatProvider (
	val id: String,
	val name: String,
	val imageUrl: String
)

