/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class FiatQuoteRequest (
	val assetId: String,
	val fiatCurrency: String,
	val fiatAmount: Double,
	val cryptoAmount: Double? = null,
	val walletAddress: String
)

