/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.Serializable

@Serializable
data class FiatQuote (
	val provider: FiatProvider,
	val fiatAmount: Double,
	val fiatCurrency: String,
	val cryptoAmount: Double,
	val redirectUrl: String
)

@Serializable
data class FiatQuotes (
	val quotes: List<FiatQuote>
)

