/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class FiatAssets (
	val version: UInt,
	val assetIds: List<String>
)

