/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class NodeState(val string: String) {
	@SerialName("active")
	Active("active"),
	@SerialName("inactive")
	Inactive("inactive"),
}

@Serializable
data class Node (
	val url: String,
	val status: NodeState,
	val priority: Int
)

@Serializable
data class ChainNode (
	val chain: String,
	val node: Node
)

@Serializable
data class ChainNodes (
	val chain: String,
	val nodes: List<Node>
)

@Serializable
data class NodesResponse (
	val version: Int,
	val nodes: List<ChainNodes>
)

