/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
enum class NodeStatus(val string: String) {
	@SerialName("active")
	Active("active"),
	@SerialName("inactive")
	Inactive("inactive"),
}

@Serializable
data class Node (
	val url: String,
	val status: NodeStatus,
	val priority: Int
)

@Serializable
data class ChainNode (
	val chain: String,
	val node: Node
)

@Serializable
data class ChainNodes (
	val chain: String,
	val nodes: List<Node>
)

@Serializable
data class NodesResponse (
	val version: Int,
	val nodes: List<ChainNodes>
)

