/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class PriceAlertDirection(val string: String) {
	@SerialName("up")
	Up("up"),
	@SerialName("down")
	Down("down"),
}

@Serializable
data class PriceAlert (
	val assetId: String,
	val currency: String,
	val price: Double? = null,
	val pricePercentChange: Double? = null,
	val priceDirection: PriceAlertDirection? = null,
	val lastNotifiedAt: Long? = null
)

@Serializable
data class PriceAlertData (
	val asset: Asset,
	val price: Price? = null,
	val priceAlert: PriceAlert
)

@Serializable
enum class PriceAlertNotificationType(val string: String) {
	@SerialName("Auto")
	Auto("Auto"),
	@SerialName("Price")
	Price("Price"),
	@SerialName("PricePercentChange")
	PricePercentChange("PricePercentChange"),
}

