/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class PushNotificationTypes(val string: String) {
	@SerialName("transaction")
	Transaction("transaction"),
	@SerialName("pricealertclient")
	PriceAlertClient("pricealertclient"),
}

@Serializable
data class PushNotification (
	val type: PushNotificationTypes,
	val data: Transaction
)

