/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class PushNotificationAsset (
	val assetId: String
)

@Serializable
enum class PushNotificationTypes(val string: String) {
	@SerialName("test")
	Test("test"),
	@SerialName("transaction")
	Transaction("transaction"),
	@SerialName("asset")
	Asset("asset"),
	@SerialName("priceAlert")
	PriceAlert("priceAlert"),
	@SerialName("buyAsset")
	BuyAsset("buyAsset"),
	@SerialName("swapAsset")
	SwapAsset("swapAsset"),
}

@Serializable
data class PushNotificationPayloadType (
	val type: PushNotificationTypes
)

@Serializable
data class PushNotificationSwapAsset (
	val fromAssetId: String,
	val toAssetId: String
)

@Serializable
data class PushNotificationTransaction (
	val walletIndex: Int,
	val assetId: String,
	val transactionId: String
)

