/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class ResponseError (
	val error: String
)

@Serializable
data class ResponseResult<T> (
	val data: T
)

