/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class ScanAddressTarget (
	val chain: Chain,
	val address: String
)

@Serializable
data class ScanTransaction (
	val isMalicious: Boolean,
	val isMemoRequired: Boolean
)

@Serializable
data class ScanTransactionPayload (
	val deviceId: String,
	val walletIndex: UInt,
	val origin: ScanAddressTarget,
	val target: ScanAddressTarget,
	val website: String? = null,
	val type: TransactionType
)

