/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class ScanAddress (
	val name: String? = null,
	val address: String,
	val isVerified: Boolean,
	val isFradulent: Boolean,
	val isMemoRequired: Boolean
)

