/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class SecurityMetadata (
	val name: String,
	val verified: Boolean,
	val requiredMemo: Boolean
)

@Serializable
data class SecurityResponse (
	val malicious: Boolean,
	val reason: String,
	val provider: String,
	val metadata: SecurityMetadata? = null
)

