/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class SecurityMetadata (
	val name: String,
	val verified: Boolean,
	val requiredMemo: Boolean
)

@Serializable
data class SecurityResponse (
	val malicious: Boolean,
	val reason: String,
	val provider: String,
	val metadata: SecurityMetadata? = null
)

