/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class SolanaTokenProgramId(val string: String) {
	@SerialName("token")
	Token("token"),
	@SerialName("token2022")
	Token2022("token2022"),
}

