/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
enum class SolanaTokenProgramId(val string: String) {
	@SerialName("token")
	Token("token"),
	@SerialName("token2022")
	Token2022("token2022"),
}

