/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class Subscription (
	val wallet_index: Int,
	val chain: Chain,
	val address: String
)

