/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class Subscription (
	val wallet_index: Int,
	val chain: Chain,
	val address: String
)

