/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SwapQuoteRequest (
	val fromAsset: String,
	val toAsset: String,
	val walletAddress: String,
	val destinationAddress: String? = null,
	val amount: String,
	val includeData: Boolean
)

@Serializable
data class SwapProvider (
	val name: String
)

@Serializable
data class SwapQuoteData (
	val to: String,
	val value: String,
	val data: String
)

@Serializable
data class SwapQuote (
	val chainType: ChainType,
	val fromAmount: String,
	val toAmount: String,
	val feePercent: Float,
	val provider: SwapProvider,
	val data: SwapQuoteData? = null
)

@Serializable
data class SwapQuoteResult (
	val quote: SwapQuote
)

@Serializable
enum class SwapMode(val string: String) {
	@SerialName("exactin")
	ExactIn("exactin"),
	@SerialName("exactout")
	ExactOut("exactout"),
}

