/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class SwapProvider(val string: String) {
	@SerialName("uniswapv3")
	UniswapV3("uniswapv3"),
	@SerialName("uniswapv4")
	UniswapV4("uniswapv4"),
	@SerialName("pancakeswapv3")
	PancakeSwapV3("pancakeswapv3"),
	@SerialName("pancakeswapaptosv2")
	PancakeSwapAptosV2("pancakeswapaptosv2"),
	@SerialName("thorchain")
	Thorchain("thorchain"),
	@SerialName("orca")
	Orca("orca"),
	@SerialName("jupiter")
	Jupiter("jupiter"),
	@SerialName("across")
	Across("across"),
	@SerialName("oku")
	Oku("oku"),
	@SerialName("wagmi")
	Wagmi("wagmi"),
	@SerialName("cetus")
	Cetus("cetus"),
	@SerialName("stonfiv2")
	StonFiV2("stonfiv2"),
	@SerialName("mayan")
	Mayan("mayan"),
	@SerialName("reservoir")
	Reservoir("reservoir"),
}

