/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
enum class TransactionState(val string: String) {
	@SerialName("pending")
	Pending("pending"),
	@SerialName("confirmed")
	Confirmed("confirmed"),
	@SerialName("failed")
	Failed("failed"),
	@SerialName("reverted")
	Reverted("reverted"),
}

