/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
enum class TransactionType(val string: String) {
	@SerialName("transfer")
	Transfer("transfer"),
	@SerialName("swap")
	Swap("swap"),
	@SerialName("tokenApproval")
	TokenApproval("tokenApproval"),
	@SerialName("stakeDelegate")
	StakeDelegate("stakeDelegate"),
	@SerialName("stakeUndelegate")
	StakeUndelegate("stakeUndelegate"),
	@SerialName("stakeRewards")
	StakeRewards("stakeRewards"),
	@SerialName("stakeRedelegate")
	StakeRedelegate("stakeRedelegate"),
	@SerialName("stakeWithdraw")
	StakeWithdraw("stakeWithdraw"),
}

