/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class TransactionExtended (
	val transaction: Transaction,
	val asset: Asset,
	val feeAsset: Asset,
	val price: Price? = null,
	val feePrice: Price? = null,
	val assets: List<Asset>
)

