/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.primitives

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class TransactionExtended (
	val transaction: Transaction,
	val asset: Asset,
	val feeAsset: Asset,
	val price: Price? = null,
	val feePrice: Price? = null,
	val assets: List<Asset>
)

