/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class UTXO (
	val transaction_id: String,
	val vout: Int,
	val value: String
)

