/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class WalletType(val string: String) {
	@SerialName("multicoin")
	multicoin("multicoin"),
	@SerialName("single")
	single("single"),
	@SerialName("privateKey")
	private_key("privateKey"),
	@SerialName("view")
	view("view"),
}

@Serializable
data class Wallet (
	val id: String,
	val name: String,
	val index: Int,
	val type: WalletType,
	val accounts: List<Account>,
	val order: Int,
	val isPinned: Boolean
)

@Serializable
data class WalletId (
	val id: String
)

