/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.blockchain.xrp.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class XRPAccount (
	val Balance: String,
	val Sequence: Int
)

@Serializable
data class XRPAssetLine (
	val currency: String
)

@Serializable
data class XRPAccountAsset (
	val LowLimit: XRPAssetLine
)

@Serializable
data class XRPAccountObjects<T> (
	val account_objects: T
)

@Serializable
data class XRPAccountResult (
	val account_data: XRPAccount? = null
)

@Serializable
data class XRPDrops (
	val minimum_fee: String,
	val median_fee: String
)

@Serializable
data class XRPFee (
	val drops: XRPDrops
)

@Serializable
data class XRPLatestBlock (
	val ledger_current_index: Long
)

@Serializable
data class XRPResult<T> (
	val result: T
)

@Serializable
data class XRPTokenId (
	val issuer: String,
	val currency: String
)

@Serializable
data class XRPTransaction (
	val hash: String
)

@Serializable
data class XRPTransactionBroadcast (
	val accepted: Boolean? = null,
	val engine_result_message: String? = null,
	val error_exception: String? = null,
	val tx_json: XRPTransaction? = null
)

@Serializable
data class XRPTransactionStatus (
	val status: String
)

