/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.blockchain.solana.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class SolanaBalance (
	val value: Long
)

@Serializable
data class SolanaBalanceValue (
	val amount: String
)

