/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.solana.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class SolanaAccount<T> (
	val lamports: Long,
	val space: Int,
	val owner: String,
	val data: T
)

@Serializable
data class SolanaAccountParsed<T> (
	val parsed: T
)

@Serializable
data class SolanaAccountParsedInfo<T> (
	val info: T
)

@Serializable
data class SolanaRentExemptReserve (
	val rentExemptReserve: String
)

@Serializable
data class SolanaStakeDelegation (
	val voter: String,
	val stake: String,
	val activationEpoch: String,
	val deactivationEpoch: String
)

@Serializable
data class SolanaStake (
	val delegation: SolanaStakeDelegation
)

@Serializable
data class SolanaStakeAccount (
	val account: SolanaAccount<SolanaAccountParsed<SolanaAccountParsedInfo<SolanaStakeInfo>>>,
	val pubkey: String
)

@Serializable
data class SolanaStakeInfo (
	val stake: SolanaStake,
	val meta: SolanaRentExemptReserve
)

@Serializable
data class SolanaTokenAccount (
	val account: SolanaAccount<SolanaAccountParsed<SolanaAccountParsedInfo<SolanaTokenInfo>>>,
	val pubkey: String
)

@Serializable
data class SolanaTokenAccountPubkey (
	val pubkey: String
)

@Serializable
data class SolanaTokenAmount (
	val amount: String
)

@Serializable
data class SolanaTokenInfo (
	val tokenAmount: SolanaTokenAmount
)

