/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.blockchain.solana.models

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.Serializable

@Serializable
object SolanaTransactionError

@Serializable
data class SolanaTransactionMeta (
	val err: SolanaTransactionError? = null
)

@Serializable
data class SolanaTransaction (
	val meta: SolanaTransactionMeta,
	val slot: Int
)

