/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.blockchain.solana.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
object SolanaTransactionError

@Serializable
data class SolanaTransactionMeta (
	val err: SolanaTransactionError? = null
)

@Serializable
data class SolanaTransaction (
	val meta: SolanaTransactionMeta,
	val slot: Int
)

