/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.blockchain.solana.models

import kotlinx.serialization.Serializable

@Serializable
data class SolanaBalance (
	val value: Long
)

@Serializable
data class SolanaBalanceValue (
	val amount: String
)

