/**
 * Generated by typeshare 1.12.0
 */

package com.wallet.core.blockchain.solana.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class SolanaPrioritizationFee (
	val prioritizationFee: Int
)

