/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.blockchain.solana.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class SolanaBlockhash (
	val blockhash: String
)

@Serializable
data class SolanaBlockhashResult (
	val value: SolanaBlockhash
)

