/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.blockchain.solana.models

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class SolanaBalance (
	val value: Long
)

@Serializable
data class SolanaBalanceValue (
	val amount: String
)

