/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.blockchain.near.models

import kotlinx.serialization.Serializable

@Serializable
data class NearAccount (
	val amount: String
)

@Serializable
data class NearAccountAccessKey (
	val nonce: Long
)

@Serializable
data class NearBlockHeader (
	val hash: String,
	val height: Long
)

@Serializable
data class NearBlock (
	val header: NearBlockHeader
)

@Serializable
data class NearBroadcastTransaction (
	val hash: String
)

@Serializable
data class NearBroadcastResult (
	val final_execution_status: String,
	val transaction: NearBroadcastTransaction
)

@Serializable
data class NearError (
	val message: String,
	val data: String? = null
)

@Serializable
data class NearGasPrice (
	val gas_price: String
)

@Serializable
data class NearGenesisConfig (
	val chain_id: String
)

@Serializable
data class NearRPCError (
	val error: NearError
)

