/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.xrp

import kotlinx.serialization.Serializable

@Serializable
data class XRPAccount (
	val Balance: String,
	val Sequence: Int,
	val OwnerCount: Int
)

@Serializable
data class XRPAssetLine (
	val currency: String
)

@Serializable
data class XRPAccountAsset (
	val LowLimit: XRPAssetLine
)

@Serializable
data class XRPAccountLine (
	val account: String,
	val balance: String,
	val currency: String
)

@Serializable
data class XRPAccountLinesResult (
	val lines: List<XRPAccountLine>? = null
)

@Serializable
data class XRPAccountObjects<T> (
	val account_objects: T
)

@Serializable
data class XRPAccountResult (
	val account_data: XRPAccount? = null,
	val ledger_current_index: Int
)

