/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.xrp

import kotlinx.serialization.Serializable

@Serializable
data class XRPTokenId (
	val issuer: String,
	val currency: String
)

