/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.xrp

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class XRPTokenId (
	val issuer: String,
	val currency: String
)

