/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.xrp

import kotlinx.serialization.Serializable

@Serializable
data class XRPLatestBlock (
	val ledger_current_index: Long
)

