/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.xrp

import kotlinx.serialization.Serializable

@Serializable
data class XRPDrops (
	val minimum_fee: String,
	val median_fee: String
)

@Serializable
data class XRPFee (
	val drops: XRPDrops
)

