/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.xrp

import kotlinx.serialization.Serializable

@Serializable
data class XRPTransaction (
	val hash: String
)

@Serializable
data class XRPTransactionBroadcast (
	val accepted: Boolean? = null,
	val engine_result_message: String? = null,
	val error_exception: String? = null,
	val tx_json: XRPTransaction? = null
)

@Serializable
data class XRPTransactionStatus (
	val status: String
)

