/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.stellar

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class StellarBalance (
	val balance: String,
	val asset_type: String,
	val asset_code: String? = null,
	val asset_issuer: String? = null
)

@Serializable
data class StellarAccount (
	val sequence: String,
	val balances: List<StellarBalance>
)

