/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.stellar

import kotlinx.serialization.Serializable

@Serializable
data class StellarAsset (
	val asset_code: String,
	val asset_issuer: String,
	val contract_id: String? = null
)

@Serializable
data class StellarRecords<T> (
	val records: List<T>
)

@Serializable
data class StellarEmbedded<T> (
	val _embedded: StellarRecords<T>
)

