/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.stellar

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class StellarFeeCharged (
	val min: String,
	val p95: String
)

@Serializable
data class StellarFees (
	val last_ledger_base_fee: String,
	val fee_charged: StellarFeeCharged
)

