/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.stellar

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class StellarNodeStatus (
	val ingest_latest_ledger: Int,
	val network_passphrase: String
)

