/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.stellar

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class StellarTransactionBroadcast (
	val hash: String? = null,
	val title: String? = null
)

@Serializable
data class StellarTransactionStatus (
	val successful: Boolean,
	val fee_charged: String
)

