/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.algorand

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class AlgorandAccountAsset (
	@SerialName("amount")
	val amount: Long,
	@SerialName("asset-id")
	val asset_id: Int
)

@Serializable
data class AlgorandAccount (
	@SerialName("amount")
	val amount: Long,
	@SerialName("assets")
	val assets: List<AlgorandAccountAsset>,
	@SerialName("min-balance")
	val min_balance: Long
)

