/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.algorand

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class AlgorandAsset (
	@SerialName("decimals")
	val decimals: Int,
	@SerialName("name")
	val name: String,
	@SerialName("unit-name")
	val unit_name: String
)

@Serializable
data class AlgorandAssetResponse (
	val params: AlgorandAsset
)

