/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.algorand

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AlgorandTransactionBroadcast (
	val txId: String? = null,
	val message: String? = null
)

@Serializable
data class AlgorandTransactionParams (
	@SerialName("min-fee")
	val min_fee: Long,
	@SerialName("genesis-id")
	val genesis_id: String,
	@SerialName("genesis-hash")
	val genesis_hash: String,
	@SerialName("last-round")
	val last_round: Long
)

@Serializable
data class AlgorandTransactionStatus (
	@SerialName("confirmed-round")
	val confirmed_round: Long
)

