/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.blockchain.algorand

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AlgorandVersions (
	@SerialName("genesis-id")
	val genesis_id: String,
	@SerialName("genesis-hash")
	val genesis_hash: String
)

