/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.blockchain.cosmos.models

import kotlinx.serialization.Serializable

@Serializable
data class CosmosSyncing (
	val syncing: Boolean
)

