/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.blockchain.cosmos.models

import kotlinx.serialization.Serializable

@Serializable
data class CosmosBalance (
	val denom: String,
	val amount: String
)

@Serializable
data class CosmosBalances (
	val balances: List<CosmosBalance>
)

