/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.blockchain.cosmos.models

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class CosmosHeader (
	val chain_id: String
)

@Serializable
data class CosmosBlock (
	val header: CosmosHeader
)

@Serializable
data class CosmosBlockResponse (
	val block: CosmosBlock
)

