/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class AddressStatus(val string: String) {
	@SerialName("multiSignature")
	MultiSignature("multiSignature"),
}

