/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class AddressName (
	val chain: Chain,
	val address: String,
	val name: String
)

