/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class BalanceMetadata (
	val votes: UInt,
	val energyAvailable: UInt,
	val energyTotal: UInt,
	val bandwidthAvailable: UInt,
	val bandwidthTotal: UInt
)

