/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class AssetPriceInfo (
	val assetId: AssetId,
	val price: Price,
	val market: AssetMarket
)

