/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class AuthNonce (
	val nonce: String,
	val timestamp: UInt
)

@Serializable
data class AuthMessage (
	val chain: Chain,
	val address: String,
	val authNonce: AuthNonce
)

@Serializable
data class AuthPayload (
	val deviceId: String,
	val chain: Chain,
	val address: String,
	val nonce: String,
	val signature: String
)

@Serializable
data class AuthenticatedRequest<T> (
	val auth: AuthPayload,
	val data: T
)

