/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class ChainAddress (
	val chain: Chain,
	val address: String
)

