/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class NFTChain(val string: String) {
	@SerialName("ethereum")
	Ethereum("ethereum"),
	@SerialName("polygon")
	Polygon("polygon"),
	@SerialName("solana")
	Solana("solana"),
	@SerialName("smartchain")
	SmartChain("smartchain"),
}

