/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class BitcoinChain(val string: String) {
	@SerialName("bitcoin")
	Bitcoin("bitcoin"),
	@SerialName("bitcoincash")
	BitcoinCash("bitcoincash"),
	@SerialName("litecoin")
	Litecoin("litecoin"),
	@SerialName("doge")
	Doge("doge"),
	@SerialName("zcash")
	Zcash("zcash"),
}

