/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class StakeChain(val string: String) {
	@SerialName("cosmos")
	Cosmos("cosmos"),
	@SerialName("osmosis")
	Osmosis("osmosis"),
	@SerialName("injective")
	Injective("injective"),
	@SerialName("sei")
	Sei("sei"),
	@SerialName("celestia")
	Celestia("celestia"),
	@SerialName("ethereum")
	Ethereum("ethereum"),
	@SerialName("solana")
	Solana("solana"),
	@SerialName("sui")
	Sui("sui"),
	@SerialName("smartchain")
	SmartChain("smartchain"),
	@SerialName("tron")
	Tron("tron"),
	@SerialName("hypercore")
	HyperCore("hypercore"),
}

