/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class ChartCandleStick (
	val date: SerializedDate,
	val open: Double,
	val high: Double,
	val low: Double,
	val close: Double,
	val volume: Double
)

@Serializable
data class ChartDateValue (
	val date: SerializedDate,
	val value: Double
)

