/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class ChartCandleStick (
	val date: SerializedDate,
	val open: Double,
	val high: Double,
	val low: Double,
	val close: Double,
	val volume: Double
)

@Serializable
data class ChartCandleUpdate (
	val coin: String,
	val interval: String,
	val candle: ChartCandleStick
)

@Serializable
data class ChartDateValue (
	val date: SerializedDate,
	val value: Double
)

@Serializable
enum class ChartLineType(val string: String) {
	@SerialName("takeProfit")
	TakeProfit("takeProfit"),
	@SerialName("stopLoss")
	StopLoss("stopLoss"),
	@SerialName("entry")
	Entry("entry"),
	@SerialName("liquidation")
	Liquidation("liquidation"),
}

@Serializable
data class ChartLine (
	val type: ChartLineType,
	val price: Double
)

