/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import com.wallet.core.primitives.swap.ApprovalData
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class ContractCallData (
	val contractAddress: String,
	val callData: String,
	val approval: ApprovalData? = null,
	val gasLimit: String? = null
)

