/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class Contact (
	val id: String,
	val name: String,
	val description: String? = null
)

@Serializable
data class ContactAddress (
	val id: String,
	val contactId: String,
	val address: String,
	val chain: Chain,
	val memo: String? = null,
	val description: String? = null
)

@Serializable
data class ContactData (
	val contact: Contact,
	val addresses: List<ContactAddress>
)

