/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
sealed class EarnType {
	@Serializable
	@SerialName("Deposit")
	data class Deposit(val content: DelegationValidator): EarnType()
	@Serializable
	@SerialName("Withdraw")
	data class Withdraw(val content: Delegation): EarnType()
}

