/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class FeePriority(val string: String) {
	@SerialName("slow")
	Slow("slow"),
	@SerialName("normal")
	Normal("normal"),
	@SerialName("fast")
	Fast("fast"),
}

@Serializable
enum class FeeUnitType(val string: String) {
	@SerialName("satVb")
	SatVb("satVb"),
	@SerialName("gwei")
	Gwei("gwei"),
	@SerialName("native")
	Native("native"),
}

