/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class FiatQuoteRequest (
	val assetId: String,
	val type: FiatQuoteType,
	val fiatCurrency: Currency,
	val fiatAmount: Double? = null,
	val cryptoValue: String? = null,
	val walletAddress: String
)

