/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class FiatQuoteType(val string: String) {
	@SerialName("buy")
	Buy("buy"),
	@SerialName("sell")
	Sell("sell"),
}

