/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class FiatQuote (
	val provider: FiatProvider,
	val type: FiatQuoteType,
	val fiatAmount: Double,
	val fiatCurrency: String,
	val cryptoAmount: Double,
	val cryptoValue: String,
	val redirectUrl: String
)

@Serializable
data class FiatQuoteError (
	val provider: String,
	val error: String
)

@Serializable
data class FiatQuotes (
	val quotes: List<FiatQuote>
)

