/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class GraphqlError (
	val message: String
)

@Serializable
data class GraphqlData<T> (
	val data: T? = null,
	val errors: List<GraphqlError>? = null
)

@Serializable
data class GraphqlRequest (
	val operationName: String,
	val variables: HashMap<String, String>,
	val query: String
)

