/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class LatencyType(val string: String) {
	@SerialName("Fast")
	Fast("Fast"),
	@SerialName("Normal")
	Normal("Normal"),
	@SerialName("Slow")
	Slow("Slow"),
}

@Serializable
data class Latency (
	val latency_type: LatencyType,
	val value: Double
)

