/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class LatencyType(val string: String) {
	@SerialName("fast")
	Fast("fast"),
	@SerialName("normal")
	Normal("normal"),
	@SerialName("slow")
	Slow("slow"),
}

@Serializable
data class Latency (
	val latency_type: LatencyType,
	val value: Double
)

