/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
sealed class CoreListItemIcon {
	@Serializable
	@SerialName("emoji")
	data class Emoji(val value: CoreEmoji): CoreListItemIcon()
	@Serializable
	@SerialName("asset")
	data class Asset(val value: AssetId): CoreListItemIcon()
	@Serializable
	@SerialName("image")
	data class Image(val value: String): CoreListItemIcon()
}

@Serializable
enum class CoreListItemBadge(val string: String) {
	@SerialName("new")
	New("new"),
}

@Serializable
data class CoreListItem (
	val id: String,
	val title: String,
	val subtitle: String? = null,
	val value: String? = null,
	val subvalue: String? = null,
	val icon: CoreListItemIcon? = null,
	val badge: CoreListItemBadge? = null,
	val url: String? = null
)

@Serializable
enum class CoreEmoji(val string: String) {
	@SerialName("gift")
	Gift("gift"),
	@SerialName("gem")
	Gem("gem"),
	@SerialName("party")
	Party("party"),
	@SerialName("warning")
	Warning("warning"),
}

