/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class MarketDominance (
	val assetId: String,
	val dominance: Float
)

@Serializable
data class MarketsAssets (
	val trending: List<AssetId>,
	val gainers: List<AssetId>,
	val losers: List<AssetId>
)

@Serializable
data class Markets (
	val marketCap: Float,
	val marketCapChangePercentage24h: Float,
	val assets: MarketsAssets,
	val dominance: List<MarketDominance>,
	val totalVolume24h: Float
)

