/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class NFTType(val string: String) {
	@SerialName("erc721")
	ERC721("erc721"),
	@SerialName("erc1155")
	ERC1155("erc1155"),
	@SerialName("spl")
	SPL("spl"),
	@SerialName("jetton")
	JETTON("jetton"),
}

@Serializable
data class NFTResource (
	val url: String,
	val mimeType: String
)

@Serializable
data class NFTImages (
	val preview: NFTResource
)

@Serializable
data class NFTAttribute (
	val name: String,
	val value: String,
	val percentage: Double? = null
)

@Serializable
data class NFTAsset (
	val id: String,
	val collectionId: String,
	val contractAddress: String? = null,
	val tokenId: String,
	val tokenType: NFTType,
	val name: String,
	val description: String? = null,
	val chain: Chain,
	val resource: NFTResource,
	val images: NFTImages,
	val attributes: List<NFTAttribute>
)

@Serializable
data class NFTCollection (
	val id: String,
	val name: String,
	val description: String? = null,
	val chain: Chain,
	val contractAddress: String,
	val images: NFTImages,
	val isVerified: Boolean,
	val links: List<AssetLink>
)

@Serializable
data class NFTAssetData (
	val collection: NFTCollection,
	val asset: NFTAsset
)

@Serializable
data class NFTAssetId (
	val chain: Chain,
	val contractAddress: String,
	val tokenId: String
)

@Serializable
data class NFTData (
	val collection: NFTCollection,
	val assets: List<NFTAsset>
)

