/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class Notification (
	val wallet_id: String,
	val notification_type: NotificationType,
	val is_read: Boolean,
	val metadata: String?? = null,
	val created_at: SerializedDate,
)

@Serializable
data class NotificationRewardsMetadata (
	val username: String,
	val points: Int
)

