/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class NotificationType(val string: String) {
	@SerialName("referralJoined")
	ReferralJoined("referralJoined"),
	@SerialName("rewardsEnabled")
	RewardsEnabled("rewardsEnabled"),
	@SerialName("rewardsCodeDisabled")
	RewardsCodeDisabled("rewardsCodeDisabled"),
}

