/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class PaymentType(val string: String) {
	@SerialName("card")
	Card("card"),
	@SerialName("google_pay")
	GooglePay("google_pay"),
	@SerialName("apple_pay")
	ApplePay("apple_pay"),
	@SerialName("cash_app")
	CashApp("cash_app"),
	@SerialName("venmo")
	Venmo("venmo"),
	@SerialName("sepa")
	Sepa("sepa"),
	@SerialName("ach")
	Ach("ach"),
	@SerialName("wire")
	Wire("wire"),
}

