/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class PaymentType(val string: String) {
	@SerialName("card")
	Card("card"),
	@SerialName("google_pay")
	GooglePay("google_pay"),
	@SerialName("apple_pay")
	ApplePay("apple_pay"),
}

