/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class PerpetualMarginType(val string: String) {
	@SerialName("cross")
	Cross("cross"),
	@SerialName("isolated")
	Isolated("isolated"),
}

@Serializable
data class PriceTarget (
	val price: Double? = null,
	val percentage: Double? = null
)

@Serializable
data class PerpetualPosition (
	val id: String,
	val perpetualId: String,
	val assetId: AssetId,
	val size: Double,
	val sizeValue: Double,
	val leverage: UByte,
	val entryPrice: Double? = null,
	val liquidationPrice: Double? = null,
	val marginType: PerpetualMarginType,
	val direction: PerpetualDirection,
	val marginAmount: Double,
	val takeProfit: PriceTarget? = null,
	val stopLoss: PriceTarget? = null,
	val pnl: Double,
	val funding: Float? = null
)

@Serializable
enum class PerpetualDirection