/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class PerpetualProvider(val string: String) {
	@SerialName("hypercore")
	Hypercore("hypercore"),
}

