/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class PerpetualMarginType(val string: String) {
	@SerialName("cross")
	Cross("cross"),
	@SerialName("isolated")
	Isolated("isolated"),
}

@Serializable
enum class PerpetualOrderType(val string: String) {
	@SerialName("market")
	Market("market"),
	@SerialName("limit")
	Limit("limit"),
}

@Serializable
data class PerpetualTriggerOrder (
	val price: Double,
	val order_type: PerpetualOrderType,
	val order_id: String
)

@Serializable
data class PerpetualPosition (
	val id: String,
	val perpetualId: String,
	val assetId: AssetId,
	val size: Double,
	val sizeValue: Double,
	val leverage: UByte,
	val entryPrice: Double? = null,
	val liquidationPrice: Double? = null,
	val marginType: PerpetualMarginType,
	val direction: PerpetualDirection,
	val marginAmount: Double,
	val takeProfit: PerpetualTriggerOrder? = null,
	val stopLoss: PerpetualTriggerOrder? = null,
	val pnl: Double,
	val funding: Float? = null
)

