/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class ChartValuePercentage (
	val date: SerializedDate,
	val value: Float,
	val percentage: Float
)

@Serializable
data class PerpetualAccountSummary (
	val accountValue: Double,
	val accountLeverage: Double,
	val marginUsage: Double,
	val unrealizedPnl: Double
)

@Serializable
data class PerpetualPortfolioTimeframeData (
	val accountValueHistory: List<ChartDateValue>,
	val pnlHistory: List<ChartDateValue>,
	val volume: Double
)

@Serializable
data class PerpetualPortfolio (
	val day: PerpetualPortfolioTimeframeData? = null,
	val week: PerpetualPortfolioTimeframeData? = null,
	val month: PerpetualPortfolioTimeframeData? = null,
	val allTime: PerpetualPortfolioTimeframeData? = null,
	val accountSummary: PerpetualAccountSummary? = null
)

@Serializable
data class PortfolioAllocation (
	val assetId: AssetId,
	val percentage: Float,
	val value: Float
)

@Serializable
data class PortfolioAsset (
	val assetId: AssetId,
	val value: String
)

@Serializable
data class PortfolioAssets (
	val totalValue: Float,
	val values: List<ChartValue>,
	val allTimeHigh: ChartValuePercentage? = null,
	val allTimeLow: ChartValuePercentage? = null,
	val allocation: List<PortfolioAllocation>
)

@Serializable
data class PortfolioAssetsRequest (
	val assets: List<PortfolioAsset>
)

@Serializable
enum class PerpetualPortfolioChartType(val string: String) {
	@SerialName("value")
	Value("value"),
	@SerialName("pnl")
	Pnl("pnl"),
}

