/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class PerpetualAccountSummary (
	val accountValue: Double,
	val accountLeverage: Double,
	val marginUsage: Double,
	val unrealizedPnl: Double
)

@Serializable
data class PerpetualPortfolioTimeframeData (
	val accountValueHistory: List<ChartDateValue>,
	val pnlHistory: List<ChartDateValue>,
	val volume: Double
)

@Serializable
data class PerpetualPortfolio (
	val day: PerpetualPortfolioTimeframeData? = null,
	val week: PerpetualPortfolioTimeframeData? = null,
	val month: PerpetualPortfolioTimeframeData? = null,
	val allTime: PerpetualPortfolioTimeframeData? = null,
	val accountSummary: PerpetualAccountSummary? = null
)

@Serializable
enum class PerpetualPortfolioChartType(val string: String) {
	@SerialName("value")
	Value("value"),
	@SerialName("pnl")
	Pnl("pnl"),
}

