/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class RecentActivityType(val string: String) {
	@SerialName("search")
	Search("search"),
	@SerialName("transfer")
	Transfer("transfer"),
	@SerialName("receive")
	Receive("receive"),
	@SerialName("fiatBuy")
	FiatBuy("fiatBuy"),
	@SerialName("fiatSell")
	FiatSell("fiatSell"),
	@SerialName("swap")
	Swap("swap"),
	@SerialName("perpetual")
	Perpetual("perpetual"),
}

