/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class ResponseError (
	val error: String
)

@Serializable
data class ResponseResult<T> (
	val data: T,
	val error: ResponseError? = null
)

