/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class RedemptionRequest (
	val id: String
)

@Serializable
enum class RewardRedemptionType(val string: String) {
	@SerialName("asset")
	Asset("asset"),
	@SerialName("giftAsset")
	GiftAsset("giftAsset"),
}

@Serializable
data class RewardRedemptionOption (
	val id: String,
	val redemptionType: RewardRedemptionType,
	val points: Int,
	val asset: Asset? = null,
	val value: String,
	val remaining: Int? = null
)

@Serializable
enum class RedemptionStatus(val string: String) {
	@SerialName("pending")
	Pending("pending"),
	@SerialName("completed")
	Completed("completed"),
	@SerialName("failed")
	Failed("failed"),
}

@Serializable
data class RewardRedemption (
	val id: Int,
	val option: RewardRedemptionOption,
	val status: RedemptionStatus,
	val transactionId: String? = null,
	val createdAt: SerializedDate
)

@Serializable
data class RedemptionResult (
	val redemption: RewardRedemption
)

@Serializable
data class ReferralQuota (
	val limit: Int,
	val available: Int
)

@Serializable
data class ReferralAllowance (
	val daily: ReferralQuota,
	val weekly: ReferralQuota
)

@Serializable
data class ReferralCode (
	val code: String
)

@Serializable
data class ReferralLeader (
	val username: String,
	val referrals: Int,
	val points: Int
)

@Serializable
data class ReferralLeaderboard (
	val daily: List<ReferralLeader>,
	val weekly: List<ReferralLeader>,
	val monthly: List<ReferralLeader>
)

@Serializable
enum class RewardEventType(val string: String) {
	@SerialName("createUsername")
	CreateUsername("createUsername"),
	@SerialName("invitePending")
	InvitePending("invitePending"),
	@SerialName("inviteNew")
	InviteNew("inviteNew"),
	@SerialName("inviteExisting")
	InviteExisting("inviteExisting"),
	@SerialName("joined")
	Joined("joined"),
	@SerialName("disabled")
	Disabled("disabled"),
}

@Serializable
data class RewardEvent (
	val event: RewardEventType,
	val points: Int,
	val createdAt: SerializedDate
)

@Serializable
data class Rewards (
	val code: String? = null,
	val referralCount: Int,
	val points: Int,
	val usedReferralCode: String? = null,
	val isEnabled: Boolean,
	val verified: Boolean,
	val redemptionOptions: List<RewardRedemptionOption>,
	val disableReason: String? = null,
	val referralAllowance: ReferralAllowance,
	val pendingVerificationAfter: SerializedDate? = null
)

