/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class RedemptionRequest (
	val id: String
)

@Serializable
enum class RewardRedemptionType(val string: String) {
	@SerialName("asset")
	Asset("asset"),
}

@Serializable
data class RewardRedemptionOption (
	val id: String,
	val redemptionType: RewardRedemptionType,
	val points: Int,
	val assetId: String? = null,
	val value: String
)

@Serializable
enum class RedemptionStatus(val string: String) {
	@SerialName("pending")
	Pending("pending"),
	@SerialName("completed")
	Completed("completed"),
	@SerialName("failed")
	Failed("failed"),
}

@Serializable
data class RewardRedemption (
	val id: Int,
	val option: RewardRedemptionOption,
	val status: RedemptionStatus,
	val transactionId: String? = null,
	val createdAt: SerializedDate
)

@Serializable
data class RedemptionResult (
	val redemption: RewardRedemption
)

@Serializable
data class ReferralCode (
	val code: String
)

@Serializable
enum class RewardEventType(val string: String) {
	@SerialName("createUsername")
	CreateUsername("createUsername"),
	@SerialName("inviteNew")
	InviteNew("inviteNew"),
	@SerialName("inviteExisting")
	InviteExisting("inviteExisting"),
	@SerialName("joined")
	Joined("joined"),
}

@Serializable
data class RewardEvent (
	val event: RewardEventType,
	val points: Int,
	val createdAt: SerializedDate
)

@Serializable
data class Rewards (
	val code: String? = null,
	val referralCount: Int,
	val points: Int,
	val usedReferralCode: String? = null,
	val isEnabled: Boolean,
	val redemptionOptions: List<RewardRedemptionOption>
)

