/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class AddressType(val string: String) {
	@SerialName("address")
	Address("address"),
	@SerialName("contract")
	Contract("contract"),
	@SerialName("validator")
	Validator("validator"),
}

@Serializable
data class ScanAddress (
	val chain: Chain,
	val address: String,
	val name: String? = null,
	val type: AddressType? = null,
	val isMalicious: Boolean? = null,
	val isMemoRequired: Boolean? = null,
	val isVerified: Boolean? = null
)

@Serializable
data class ScanAddressTarget (
	val chain: Chain,
	val address: String
)

@Serializable
data class ScanTransaction (
	val isMalicious: Boolean,
	val isMemoRequired: Boolean
)

@Serializable
data class ScanTransactionPayload (
	val deviceId: String,
	val walletIndex: UInt,
	val origin: ScanAddressTarget,
	val target: ScanAddressTarget,
	val website: String? = null,
	val type: TransactionType
)

