/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class SearchResponse (
	val assets: List<AssetBasic>,
	val perpetuals: List<Perpetual>,
	val nfts: List<NFTCollection>
)

@Serializable
enum class SearchItemType(val string: String) {
	@SerialName("asset")
	Asset("asset"),
	@SerialName("perpetual")
	Perpetual("perpetual"),
	@SerialName("nft")
	Nft("nft"),
}

