/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class SimulationBalanceChange (
	val assetId: AssetId,
	val value: String
)

@Serializable
data class SimulationHeader (
	val assetId: AssetId,
	val value: String
)

@Serializable
enum class SimulationPayloadFieldKind(val string: String) {
	@SerialName("contract")
	Contract("contract"),
	@SerialName("method")
	Method("method"),
	@SerialName("token")
	Token("token"),
	@SerialName("spender")
	Spender("spender"),
	@SerialName("value")
	Value("value"),
	@SerialName("custom")
	Custom("custom"),
}

@Serializable
enum class SimulationPayloadFieldType(val string: String) {
	@SerialName("text")
	Text("text"),
	@SerialName("address")
	Address("address"),
	@SerialName("timestamp")
	Timestamp("timestamp"),
}

@Serializable
enum class SimulationPayloadFieldDisplay(val string: String) {
	@SerialName("primary")
	Primary("primary"),
	@SerialName("secondary")
	Secondary("secondary"),
}

@Serializable
data class SimulationPayloadField (
	val kind: SimulationPayloadFieldKind,
	val label: String? = null,
	val value: String,
	val fieldType: SimulationPayloadFieldType,
	val display: SimulationPayloadFieldDisplay
)

@Serializable
enum class SimulationSeverity(val string: String) {
	@SerialName("low")
	Low("low"),
	@SerialName("warning")
	Warning("warning"),
	@SerialName("critical")
	Critical("critical"),
}

enum class SimulationWarningType

@Serializable
data class SimulationWarning (
	val severity: SimulationSeverity,
	val warning: SimulationWarningType,
	val message: String? = null
)

@Serializable
data class SimulationResult (
	val warnings: List<SimulationWarning>,
	val balanceChanges: List<SimulationBalanceChange>,
	val payload: List<SimulationPayloadField>,
	val header: SimulationHeader? = null
)

