/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class SolanaAccountMeta (
	val pubkey: String,
	val isSigner: Boolean,
	val isWritable: Boolean
)

@Serializable
data class SolanaInstruction (
	val programId: String,
	val accounts: List<SolanaAccountMeta>,
	val data: String
)

