/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class StakeProviderType(val string: String) {
	@SerialName("stake")
	Stake("stake"),
	@SerialName("earn")
	Earn("earn"),
}

