/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class StreamBalanceUpdate (
	val walletId: WalletId,
	val chain: Chain,
	val address: String,
	val assetId: AssetId
)

@Serializable
data class StreamMessagePrices (
	val assets: List<AssetId>
)

@Serializable
data class StreamTransactionsUpdate (
	val walletId: WalletId,
	val transactions: List<Transaction>
)

@Serializable
sealed class StreamEvent {
	@Serializable
	@SerialName("prices")
	data class Prices(val data: WebSocketPricePayload): StreamEvent()
	@Serializable
	@SerialName("balances")
	data class Balances(val data: List<StreamBalanceUpdate>): StreamEvent()
	@Serializable
	@SerialName("transactions")
	data class Transactions(val data: StreamTransactionsUpdate): StreamEvent()
}

@Serializable
sealed class StreamMessage {
	@Serializable
	@SerialName("subscribePrices")
	data class SubscribePrices(val data: StreamMessagePrices): StreamMessage()
	@Serializable
	@SerialName("unsubscribePrices")
	data class UnsubscribePrices(val data: StreamMessagePrices): StreamMessage()
	@Serializable
	@SerialName("addPrices")
	data class AddPrices(val data: StreamMessagePrices): StreamMessage()
}

