/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class StreamBalanceUpdate (
	val walletId: WalletId,
	val assetId: AssetId
)

@Serializable
data class StreamMessagePrices (
	val assets: List<AssetId>
)

@Serializable
data class StreamNftUpdate (
	val walletId: WalletId
)

@Serializable
data class StreamNotificationlUpdate (
	val walletId: WalletId,
	val notification: InAppNotification
)

@Serializable
data class StreamPerpetualUpdate (
	val walletId: WalletId
)

@Serializable
data class StreamPriceAlertUpdate (
	val assets: List<AssetId>
)

@Serializable
data class StreamTransactionsUpdate (
	val walletId: WalletId,
	val transactions: List<String>
)

@Serializable
sealed class StreamEvent {
	@Serializable
	@SerialName("prices")
	data class Prices(val data: WebSocketPricePayload): StreamEvent()
	@Serializable
	@SerialName("balances")
	data class Balances(val data: List<StreamBalanceUpdate>): StreamEvent()
	@Serializable
	@SerialName("transactions")
	data class Transactions(val data: StreamTransactionsUpdate): StreamEvent()
	@Serializable
	@SerialName("priceAlerts")
	data class PriceAlerts(val data: StreamPriceAlertUpdate): StreamEvent()
	@Serializable
	@SerialName("nft")
	data class Nft(val data: StreamNftUpdate): StreamEvent()
	@Serializable
	@SerialName("perpetual")
	data class Perpetual(val data: StreamPerpetualUpdate): StreamEvent()
	@Serializable
	@SerialName("inAppNotification")
	data class InAppNotification(val data: StreamNotificationlUpdate): StreamEvent()
}

@Serializable
sealed class StreamMessage {
	@Serializable
	@SerialName("subscribePrices")
	data class SubscribePrices(val data: StreamMessagePrices): StreamMessage()
	@Serializable
	@SerialName("unsubscribePrices")
	data class UnsubscribePrices(val data: StreamMessagePrices): StreamMessage()
	@Serializable
	@SerialName("addPrices")
	data class AddPrices(val data: StreamMessagePrices): StreamMessage()
	@Serializable
	@SerialName("subscribeRealtimePrices")
	data class SubscribeRealtimePrices(val data: StreamMessagePrices): StreamMessage()
	@Serializable
	@SerialName("unsubscribeRealtimePrices")
	data class UnsubscribeRealtimePrices(val data: StreamMessagePrices): StreamMessage()
}

