/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class AddressChains (
	val address: String,
	val chains: List<Chain>
)

@Serializable
data class WalletSubscription (
	val walletId: String,
	val source: WalletSource? = null,
	val subscriptions: List<AddressChains>
)

@Serializable
data class WalletSubscriptionChains (
	val walletId: String,
	val chains: List<Chain>
)

