/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class Subscription (
	val wallet_index: Int,
	val chain: Chain,
	val address: String
)

@Serializable
data class WalletSubscription (
	val wallet_id: String,
	val source: WalletSource,
	val subscriptions: List<ChainAddress>
)

@Serializable
data class WalletSubscriptionChains (
	val wallet_id: String,
	val chains: List<Chain>
)

