/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class SupportDevice (
	val supportId: String,
	val deviceId: String,
	val unread: Int
)

