/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class NewSupportDevice (
	val supportDeviceId: String,
	val deviceId: String
)

@Serializable
data class SupportDevice (
	val supportDeviceId: String,
	val unread: Int
)

