/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class SwapProvider(val string: String) {
	@SerialName("uniswap_v3")
	UniswapV3("uniswap_v3"),
	@SerialName("uniswap_v4")
	UniswapV4("uniswap_v4"),
	@SerialName("pancakeswap_v3")
	PancakeswapV3("pancakeswap_v3"),
	@SerialName("aerodrome")
	Aerodrome("aerodrome"),
	@SerialName("pancakeswap_aptos_v2")
	PancakeswapAptosV2("pancakeswap_aptos_v2"),
	@SerialName("thorchain")
	Thorchain("thorchain"),
	@SerialName("jupiter")
	Jupiter("jupiter"),
	@SerialName("across")
	Across("across"),
	@SerialName("oku")
	Oku("oku"),
	@SerialName("wagmi")
	Wagmi("wagmi"),
	@SerialName("cetus")
	Cetus("cetus"),
	@SerialName("stonfi_v2")
	StonfiV2("stonfi_v2"),
	@SerialName("mayan")
	Mayan("mayan"),
	@SerialName("reservoir")
	Reservoir("reservoir"),
	@SerialName("symbiosis")
	Symbiosis("symbiosis"),
	@SerialName("chainflip")
	Chainflip("chainflip"),
	@SerialName("cetus_aggregator")
	CetusAggregator("cetus_aggregator"),
	@SerialName("relay")
	Relay("relay"),
	@SerialName("hyperliquid")
	Hyperliquid("hyperliquid"),
}

