/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class TpslType(val string: String) {
	@SerialName("takeProfit")
	TakeProfit("takeProfit"),
	@SerialName("stopLoss")
	StopLoss("stopLoss"),
}

