/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class TransactionNFTTransferMetadata (
	val assetId: NFTAssetId
)

@Serializable
data class TransactionSwapMetadata (
	val fromAsset: AssetId,
	val fromValue: String,
	val toAsset: AssetId,
	val toValue: String,
	val provider: String? = null
)

