/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class TransactionNFTTransferMetadata (
	val assetId: String,
	val name: String? = null
)

@Serializable
data class TransactionPerpetualMetadata (
	val pnl: Double,
	val price: Double,
	val direction: PerpetualDirection,
	val provider: PerpetualProvider? = null
)

@Serializable
data class TransactionSwapMetadata (
	val fromAsset: AssetId,
	val fromValue: String,
	val toAsset: AssetId,
	val toValue: String,
	val provider: String? = null
)

