/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class TransactionUtxoInput (
	val address: String,
	val value: String
)

