/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable

@Serializable
data class TransactionExtended (
	val transaction: Transaction,
	val asset: Asset,
	val feeAsset: Asset,
	val price: Price? = null,
	val feePrice: Price? = null,
	val assets: List<Asset>,
	val prices: List<AssetPrice>,
	val fromAddress: AddressName? = null,
	val toAddress: AddressName? = null
)

