/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class VerificationStatus(val string: String) {
	@SerialName("verified")
	Verified("verified"),
	@SerialName("unverified")
	Unverified("unverified"),
	@SerialName("suspicious")
	Suspicious("suspicious"),
}

