/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class WalletConnectionState(val string: String) {
	@SerialName("started")
	Started("started"),
	@SerialName("active")
	Active("active"),
	@SerialName("expired")
	Expired("expired"),
}

@Serializable
data class WalletConnectionSessionAppMetadata (
	val name: String,
	val description: String,
	val url: String,
	val icon: String
)

@Serializable
data class WalletConnectionSession (
	val id: String,
	val sessionId: String,
	val state: WalletConnectionState,
	val chains: List<Chain>,
	val createdAt: SerializedDate,
	val expireAt: SerializedDate,
	val metadata: WalletConnectionSessionAppMetadata
)

@Serializable
data class WalletConnection (
	val session: WalletConnectionSession,
	val wallet: Wallet
)

@Serializable
data class WalletConnectionSessionProposal (
	val defaultWallet: Wallet,
	val wallets: List<Wallet>,
	val metadata: WalletConnectionSessionAppMetadata
)

@Serializable
enum class WalletConnectionEvents(val string: String) {
	@SerialName("connect")
	Connect("connect"),
	@SerialName("disconnect")
	Disconnect("disconnect"),
	@SerialName("accountsChanged")
	AccountsChanged("accountsChanged"),
	@SerialName("chainChanged")
	ChainChanged("chainChanged"),
}

@Serializable
enum class WalletConnectionMethods(val string: String) {
	@SerialName("eth_chainId")
	EthChainId("eth_chainId"),
	@SerialName("eth_sign")
	EthSign("eth_sign"),
	@SerialName("personal_sign")
	PersonalSign("personal_sign"),
	@SerialName("eth_signTypedData")
	EthSignTypedData("eth_signTypedData"),
	@SerialName("eth_signTypedData_v4")
	EthSignTypedDataV4("eth_signTypedData_v4"),
	@SerialName("eth_signTransaction")
	EthSignTransaction("eth_signTransaction"),
	@SerialName("eth_sendTransaction")
	EthSendTransaction("eth_sendTransaction"),
	@SerialName("eth_sendRawTransaction")
	EthSendRawTransaction("eth_sendRawTransaction"),
	@SerialName("wallet_switchEthereumChain")
	WalletSwitchEthereumChain("wallet_switchEthereumChain"),
	@SerialName("wallet_addEthereumChain")
	WalletAddEthereumChain("wallet_addEthereumChain"),
	@SerialName("solana_signMessage")
	SolanaSignMessage("solana_signMessage"),
	@SerialName("solana_signTransaction")
	SolanaSignTransaction("solana_signTransaction"),
	@SerialName("solana_signAndSendTransaction")
	SolanaSignAndSendTransaction("solana_signAndSendTransaction"),
	@SerialName("solana_signAllTransactions")
	SolanaSignAllTransactions("solana_signAllTransactions"),
	@SerialName("sui_signPersonalMessage")
	SuiSignPersonalMessage("sui_signPersonalMessage"),
	@SerialName("sui_signTransaction")
	SuiSignTransaction("sui_signTransaction"),
	@SerialName("sui_signAndExecuteTransaction")
	SuiSignAndExecuteTransaction("sui_signAndExecuteTransaction"),
}

