/**
 * Generated by typeshare 1.13.3
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class WalletSource(val string: String) {
	@SerialName("create")
	Create("create"),
	@SerialName("import")
	Import("import"),
}

@Serializable
data class Wallet (
	val id: String,
	val externalId: String? = null,
	val name: String,
	val index: Int,
	val type: WalletType,
	val accounts: List<Account>,
	val order: Int,
	val isPinned: Boolean,
	val imageUrl: String? = null,
	val source: WalletSource
)

