/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
enum class WalletConnectEthereumMethods(val string: String) {
	@SerialName("chainId")
	chain_id("chainId"),
	@SerialName("sign")
	sign("sign"),
	@SerialName("personalSign")
	personal_sign("personalSign"),
	@SerialName("signTypedData")
	sign_typed_data("signTypedData"),
	@SerialName("signTypedDataV4")
	sign_typed_data_v4("signTypedDataV4"),
	@SerialName("signTransaction")
	sign_transaction("signTransaction"),
	@SerialName("sendTransaction")
	send_transaction("sendTransaction"),
	@SerialName("sendRawTransaction")
	send_raw_transaction("sendRawTransaction"),
	@SerialName("switchChain")
	switch_chain("switchChain"),
	@SerialName("addChain")
	add_chain("addChain"),
}

@Serializable
enum class WalletConnectSolanaMethods(val string: String) {
	@SerialName("signMessage")
	sign_message("signMessage"),
	@SerialName("signTransaction")
	sign_transaction("signTransaction"),
	@SerialName("signAndSendTransaction")
	sign_and_send_transaction("signAndSendTransaction"),
	@SerialName("signAllTransactions")
	sign_all_transactions("signAllTransactions"),
}

