/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class WCEthereumTransaction (
	val chainId: String? = null,
	val from: String,
	val to: String,
	val value: String? = null,
	val gas: String? = null,
	val gasLimit: String? = null,
	val gasPrice: String? = null,
	val maxFeePerGas: String? = null,
	val maxPriorityFeePerGas: String? = null,
	val nonce: String? = null,
	val data: String? = null
)

