/**
 * Generated by typeshare 1.13.2
 */

package com.wallet.core.primitives

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class WebSocketPriceActionType(val string: String) {
	@SerialName("subscribe")
	Subscribe("subscribe"),
	@SerialName("add")
	Add("add"),
}

@Serializable
data class WebSocketPriceAction (
	val action: WebSocketPriceActionType,
	val assets: List<AssetId>? = null
)

@Serializable
data class WebSocketPricePayload (
	val prices: List<AssetPrice>,
	val rates: List<FiatRate>
)

