/**
 * Generated by typeshare 1.11.0
 */

package com.wallet.core.blockchain.tron.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

@Serializable
data class TronAccount (
	val balance: Long? = null,
	val address: String? = null
)

@Serializable
data class TronAccountRequest (
	val address: String,
	val visible: Boolean
)

@Serializable
data class TronAccountUsage (
	val freeNetUsed: Int? = null,
	val freeNetLimit: Int? = null
)

@Serializable
data class TronEmptyAccount (
	val address: String? = null
)

