/**
 * Generated by typeshare 1.9.2
 */

@file:NoLiveLiterals

package com.wallet.core.blockchain.tron.models

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class TronHeader (
	val number: Long,
	val version: Long,
	val txTrieRoot: String,
	val witness_address: String,
	val parentHash: String,
	val timestamp: Long
)

@Serializable
data class TronHeaderRawData (
	val raw_data: TronHeader
)

@Serializable
data class TronBlock (
	val block_header: TronHeaderRawData
)

